// Generado por scripts/process_art.py. No editar a mano.

export const SPRITES = {
  "char-arm": { file: "char-arm.png", w: 26, h: 80 },
  "char-arm-tint": { file: "char-arm-tint.png", w: 26, h: 80 },
  "char-head": { file: "char-head.png", w: 55, h: 59 },
  "char-head-dizzy": { file: "char-head-dizzy.png", w: 55, h: 59 },
  "char-head-scream": { file: "char-head-scream.png", w: 58, h: 62 },
  "char-leg": { file: "char-leg.png", w: 42, h: 78 },
  "char-torso": { file: "char-torso.png", w: 64, h: 75 },
  "char-torso-tint": { file: "char-torso-tint.png", w: 64, h: 75 },
  "fx-bubbles": { file: "fx-bubbles.png", w: 88, h: 87 },
  "fx-burst": { file: "fx-burst.png", w: 196, h: 163 },
  "fx-confetti-0": { file: "fx-confetti-0.png", w: 24, h: 25 },
  "fx-confetti-1": { file: "fx-confetti-1.png", w: 22, h: 23 },
  "fx-confetti-10": { file: "fx-confetti-10.png", w: 17, h: 18 },
  "fx-confetti-11": { file: "fx-confetti-11.png", w: 18, h: 17 },
  "fx-confetti-12": { file: "fx-confetti-12.png", w: 14, h: 15 },
  "fx-confetti-13": { file: "fx-confetti-13.png", w: 15, h: 13 },
  "fx-confetti-14": { file: "fx-confetti-14.png", w: 15, h: 14 },
  "fx-confetti-2": { file: "fx-confetti-2.png", w: 20, h: 22 },
  "fx-confetti-3": { file: "fx-confetti-3.png", w: 21, h: 22 },
  "fx-confetti-4": { file: "fx-confetti-4.png", w: 18, h: 22 },
  "fx-confetti-5": { file: "fx-confetti-5.png", w: 21, h: 15 },
  "fx-confetti-6": { file: "fx-confetti-6.png", w: 20, h: 21 },
  "fx-confetti-7": { file: "fx-confetti-7.png", w: 20, h: 18 },
  "fx-confetti-8": { file: "fx-confetti-8.png", w: 18, h: 18 },
  "fx-confetti-9": { file: "fx-confetti-9.png", w: 16, h: 19 },
  "fx-puff": { file: "fx-puff.png", w: 146, h: 126 },
  "fx-splash": { file: "fx-splash.png", w: 214, h: 149 },
  "fx-star": { file: "fx-star.png", w: 47, h: 48 },
  "prop-arch": { file: "prop-arch.png", w: 432, h: 302 },
  "prop-bumper": { file: "prop-bumper.png", w: 114, h: 358 },
  "prop-pillar": { file: "prop-pillar.png", w: 106, h: 170 },
  "prop-roller": { file: "prop-roller.png", w: 222, h: 221 },
  "prop-water": { file: "prop-water.png", w: 298, h: 105 },
} as const;

export type SpriteName = keyof typeof SPRITES;
